kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: wiremock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wiremock
        version: v1
    spec:
      volumes:
        - name: mappings
          configMap:
            name: wiremock-mappings
        - name: files
          configMap:
            name: wiremock-files
      containers:
      - name: wiremock
        image: rodolpheche/wiremock:2.24.0-alpine
        imagePullPolicy: Always
        volumeMounts:
          - name: mappings
            mountPath: /home/wiremock/mappings
          - name: files
            mountPath: /home/wiremock/__files
      restartPolicy: Always
